name: Playwright Tests with Sharding

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  install-playwright:
    name: Install Playwright Browsers
    runs-on: ubuntu-latest
    outputs:
      playwright-path: ${{ steps.install.outputs.playwright-path }} # Output the path to Playwright
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        id: install
        run: |
          npm i playwright # Install Playwright locally
          npx playwright install --with-deps
          echo "playwright-path=$(npm root)/playwright" >> $GITHUB_OUTPUT # Output the path
      
      - name: Upload Playwright installation
        uses: actions/upload-artifact@v4
        with:
          name: playwright-installation
          path: node_modules/playwright # Upload the playwright installation directory
          retention-days: 1


  test:
    name: 'Playwright Tests - Shard ${{ matrix.shard }}'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [install-playwright] # This job depends on playwright installation

    strategy:
      fail-fast: false
      matrix:
        shard: [1/3, 2/3, 3/3] # You mentioned 2 shards, but matrix still shows 3. Adjust as needed.

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      
      - name: Download Playwright installation
        uses: actions/download-artifact@v4
        with:
          name: playwright-installation
          path: node_modules/playwright # Download to the correct location

      - name: Run Playwright tests
        run: npx playwright test specs/e2e/ --shard ${{ matrix.shard }} --workers=2 --reporter=blob

      - name: Prepare blob report name
        id: prep
        run: echo "name=blob-report-$(echo '${{ matrix.shard }}' | sed 's/\//-/g')" >> $GITHUB_OUTPUT
      
      - name: Upload blob report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prep.outputs.name }}
          path: blob-report
          retention-days: 30

  merge-reports:
    name: Merge Reports
    if: always()
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Download blob reports from all shards
        uses: actions/download-artifact@v4
        with:
          pattern: blob-report-*
          path: all-blob-reports
          merge-multiple: false
      
      - name: Debug directory structure
        run: |
          ls -R all-blob-reports
          find all-blob-reports -type d -name "blob-report"
      
      - name: Merge into HTML Report
        run: |
          npx playwright merge-reports --reporter html all-blob-reports/blob-report-*/blob-report

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-html-report
          path: playwright-report
          retention-days: 30
